version: "3.8"

services:
  nest-api:
    build: ./apps/nest-api
    ports:
      - "6070:6070"
    environment:
      - NODE_ENV=production

  go-app:
    build: ./apps/go-api
    ports:
      - "6060:6060"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
