openapi: 2.0.0
info:
  title: My Custom API
  description: This is a sample API for demonstration purposes.
  version: 1.0.0

servers:
  - url: https://my-custom-api.com/v1
    description: Main production server

paths:
  /user/me:
    get:
      summary: Get current user information
      operationId: getUser
      tags:
        - User
      responses:
        "200":
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The user ID.
                    example: "12345"
                  username:
                    type: string
                    description: The user's username.
                    example: "john_doe"
                  email:
                    type: string
                    description: The user's email.
                    example: "john@example.com"
        "401":
          description: Unauthorized
        "404":
          description: User not found
